"""initial schema

Revision ID: 6c008000db26
Revises: 
Create Date: 2026-09-18 07:45:44.650543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c008000db26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_balance', sa.Numeric(), nullable=False),
    sa.Column('final_balance', sa.Numeric(), nullable=True),
    sa.Column('win_rate', sa.Numeric(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(), nullable=True),
    sa.Column('profit_factor', sa.Numeric(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Numeric(), nullable=False),
    sa.Column('exit_price', sa.Numeric(), nullable=True),
    sa.Column('pnl', sa.Numeric(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('strategy_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_pct_per_trade', sa.Numeric(), nullable=False),
    sa.Column('max_daily_loss_pct', sa.Numeric(), nullable=False),
    sa.Column('max_concurrent_positions', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='bot_config_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('circuit_breaker_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trading_day', sa.Date(), nullable=False),
    sa.Column('starting_equity', sa.Numeric(), nullable=False),
    sa.Column('realized_pnl_today', sa.Numeric(), nullable=False),
    sa.Column('halted', sa.Boolean(), nullable=False),
    sa.Column('halted_reason', sa.String(), nullable=True),
    sa.Column('halted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trading_day')
    )
    op.create_table('equity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('equity', sa.Numeric(), nullable=False),
    sa.Column('open_positions_count', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_trade_id', sa.String(), nullable=True),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('volume', sa.Numeric(), nullable=False),
    sa.Column('entry_price', sa.Numeric(), nullable=True),
    sa.Column('stop_loss_price', sa.Numeric(), nullable=False),
    sa.Column('take_profit_price', sa.Numeric(), nullable=True),
    sa.Column('trailing_stop_distance', sa.Numeric(), nullable=True),
    sa.Column('exit_price', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('close_reason', sa.String(), nullable=True),
    sa.Column('pnl', sa.Numeric(), nullable=True),
    sa.Column('pnl_pct', sa.Numeric(), nullable=True),
    sa.Column('risk_amount', sa.Numeric(), nullable=True),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('signal_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('equity_snapshots')
    op.drop_table('circuit_breaker_state')
    op.drop_table('bot_config')
    op.drop_table('backtest_trades')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
